---
title: "`r params$set_title`"
institution: "NYU"
date: "12/15/2017"
fontsize: 10pt
output: 
    slidy_presentation: 
      self_contained: true
      fig_retina: 100
      keep_md: yes
      footer: "`r params$set_title`"
    beamer_presentation:
      keep_tex: yes
      theme: "CambridgeUS"
      colortheme: "dove"
      fonttheme: "structurebold"
      includes:
        in_header: default.tex
params: 
    set_title: " Predicting crime rates using taxi rides in NYC"
    set_authors: "Carlos Petricioli (cpa253),
    Varsha Muralidharan  (vm1370) and
    Valerie Angulo (vaa238) "
---

## Big Data Analytics Symposium - Fall 2017

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Analytics Project

`r params$set_title`

### Team

- Carlos Petricioli (cpa253)

- Varsha Muralidharan  (vm1370)

- Valerie Angulo (vaa238)

### Abstract

- We study crime rates and its relationship on how people use of taxis in New York City. 
- Our hypothesis is that people are less likely to walk in areas subjectively deemed more dangerous and will instead opt to use more reliable and immediate transportation such as designated taxis. 
- WE FOUND THAT ____. 


# `r params$set_title`

## Motivation
### Who are the users of this analytic?         
< Short description of why this analytic is important > 

### who will benefit?
BENEFIT


### Why is this analytic important?         
< Short description of why this analytic is important > 

## Goodness

### cleaning data
we made sure that --

### model testing
we made sure that --

## Data Sources

Name:           <Data Source 1 Name>
Description:  <Brief description…>
Size of data:  <Size…>

Name:           <Data Source 2 Name>
Description:  <Brief description…>
Size of data:  <Size…>
…
Name:           <Data Source n Name>
Description:  <Brief description…>
Size of data:  <Size…>

## Design Diagram

< Insert one or more design diagrams here. Diagrams should show inputs, outputs, tools used. >

Platform(s) on which the analytic ran: 
< Did you use the Quickstart VM? NYU HPC cluster? Amazon AWS? Google GCE? Multiple platforms? >

## Results

1. <Result 1>
< Tell us a maximum of three results, insights, observations, or outcomes… >

2. <Result 2>

3. <Result 3>

## Obstacles

1. <Obstacle1>
< Tell us up to two obstacles you experienced in developing this analytic. >

2. <Obstacle 2>

## Summary

<Brief wrap-up!>



## Acknowledgements

<
If you used an Amazon AWS voucher for this work, thank Amazon here.
If you had help from HPC, thank them for their support here.
If you received data from some source that was kind enough to share their data with you, thank them here.
If you worked with a domain expert, you know what to do…
>

## References

< List the work you referenced >


# Thank you!
